version: '3'

services:
  go_bot:
    image: go_bot_image
    environment:
      - "TELEGA_TOKEN=6494268029:AAFynGSIs4CCOZrDEsZpsWZElUctsZa44-w"
      - "API_KEY=3ba6283321msh80a967930e01301p13ea9fjsna2afafa73bdc"
      - "HOST=mashape-community-urban-dictionary.p.rapidapi.com"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
