version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  go_bot:
    image: go_bot_image
    environment:
      - "TELEGA_TOKEN=$TELEGA_TOKEN"
      - "API_KEY=$API_KEY"
      - "HOST=$HOST"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis

volumes:
  redis_data:
